---
name: 'Renovate'

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Dry-Run'
        default: 'false'
        required: false
      logLevel:
        description: 'Log-Level'
        default: 'debug'
        required: false
  schedule:
    - cron: '0 * * * *'
  push:
    branches: ['main']
    paths:
      - '.github/renovate.json5'
      - '.github/renovate/**.json5'

env:
  LOG_LEVEL: debug
  RENOVATE_DRY_RUN: false
  RENOVATE_CONFIG_FILE: .github/renovate.json5

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Generate Token
        uses: tibdex/github-app-token@32691ba7c9e7063bd457bd8f2a5703138591fa58 # v1.9.0
        id: generate-token
        with:
          app_id: '${{ secrets.TRUXNELL_APP_ID }}'
          private_key: '${{ secrets.TRUXNELL_APP_PRIVATE_KEY }}'

      - name: Override default config from dispatch variables
        run: |
          echo "RENOVATE_DRY_RUN=${{ github.event.inputs.dryRun || env.RENOVATE_DRY_RUN }}" >> "${GITHUB_ENV}"
          echo "LOG_LEVEL=${{ github.event.inputs.logLevel || env.LOG_LEVEL }}" >> "${GITHUB_ENV}"

      - name: Renovate
        uses: renovatebot/github-action@5c6c06aa0e3d7a6a9b6cba05c078c51631b5f11a # v39.1.1
        with:
          configurationFile: '${{ env.RENOVATE_CONFIG_FILE }}'
          token: '${{ steps.generate-token.outputs.token }}'
